# Generated by Django 5.2.1 on 2025-12-10 19:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperMemo',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paper Memo',
                'verbose_name_plural': 'Paper Memos',
            },
        ),
        migrations.CreateModel(
            name='QuestionMemo',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('question_number', models.CharField(db_index=True, max_length=50)),
                ('content', models.TextField(help_text='Memo/answer content')),
                ('notes', models.TextField(blank=True, help_text='Additional notes/warnings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question Memo',
                'ordering': ['question_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='examnode',
            options={'ordering': ['paper', 'order_index'], 'verbose_name': 'Exam Node', 'verbose_name_plural': 'Exam Nodes'},
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['-created_at'], 'verbose_name': 'Paper', 'verbose_name_plural': 'Papers'},
        ),
        migrations.AlterModelOptions(
            name='regexpattern',
            options={'ordering': ['-match_score', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='examnode',
            name='core_examno_paper_i_3b1059_idx',
        ),
        migrations.RemoveIndex(
            model_name='examnode',
            name='core_examno_paper_i_686969_idx',
        ),
        migrations.RemoveField(
            model_name='examnode',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='is_randomized',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='examnode',
            name='manifest_output_dir',
            field=models.CharField(blank=True, help_text='Path to extracted media', max_length=500),
        ),
        migrations.AddField(
            model_name='paper',
            name='parent_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='randomised_variants', to='core.paper'),
        ),
        migrations.AddField(
            model_name='regexpattern',
            name='format_signature',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='examnode',
            name='id',
            field=models.CharField(editable=False, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='examnode',
            name='marks',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='examnode',
            name='node_type',
            field=models.CharField(choices=[('question', 'Question'), ('instruction', 'Instruction/Rubric'), ('table', 'Table'), ('image', 'Image/Figure'), ('pagebreak', 'Page Break'), ('case_study', 'Case Study'), ('paragraph', 'Paragraph')], default='paragraph', max_length=20),
        ),
        migrations.AlterField(
            model_name='examnode',
            name='number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='examnode',
            name='order_index',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='examnode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.examnode'),
        ),
        migrations.AlterField(
            model_name='examnode',
            name='text',
            field=models.TextField(blank=True, default='', help_text='Plain text preview/summary'),
        ),
        migrations.AlterField(
            model_name='extractorblock',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paper',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paper',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paper',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='core.qualification'),
        ),
        migrations.AlterField(
            model_name='regexpattern',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='regexpattern',
            name='example_usage',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='regexpattern',
            name='match_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='papermemo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='papermemo',
            name='paper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memo', to='core.paper'),
        ),
        migrations.AddField(
            model_name='questionmemo',
            name='exam_node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memo', to='core.examnode'),
        ),
        migrations.AddField(
            model_name='questionmemo',
            name='paper_memo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.papermemo'),
        ),
    ]
