# Generated by Django 5.2.1 on 2025-12-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_papermemo_questionmemo_alter_examnode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_randomized',
            field=models.BooleanField(default=False),
        ),
    ]
