# Generated by Django 5.2.1 on 2025-12-10 20:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_paper_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examnode',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
