# Generated by Django 5.2.1 on 2026-01-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_assessmentstatusnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_moderation', 'Pending Moderation'), ('moderated', 'Moderated'), ('pending_etqa', 'Pending ETQA Review'), ('etqa_approved', 'ETQA Approved'), ('etqa_rejected', 'ETQA Rejected'), ('pending_qcto', 'Pending QCTO Review'), ('qcto_approved', 'QCTO Approved'), ('qcto_rejected', 'QCTO Rejected'), ('Released to students', 'Released to students'), ('active', 'Active'), ('archived', 'Archived'), ('QDD Review', 'QDD Review')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('default', 'Awaiting Activation'), ('admin', 'Administrator'), ('assessor_dev', 'Assessor (Developer)'), ('moderator', 'Moderator (Developer)'), ('qcto', 'QCTO Validator'), ('etqa', 'ETQA'), ('qdd', 'QDD Reviewer'), ('learner', 'Learner'), ('assessor_marker', 'Assessor (Marker)'), ('internal_mod', 'Internal Moderator'), ('external_mod', 'External Moderator (QALA)'), ('assessment_center', 'Assessment Center')], default='admin', max_length=30),
        ),
    ]
